In [18]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [12]:
class Demo2:
    
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display

SyntaxError: invalid syntax (<ipython-input-12-02769d7a2b82>, line 7)

In [20]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [10]:
# some inheritance
# parent class
class person():
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isEmployee(self):
        return False
# derived class
class Employee(person):
    def isEmployee(self):
        return True
    
    

emp=person("Anil")
print(emp.getname(),emp.isEmployee())

emp1=employee("Akhil")
print(emp.getname(),emp.isEmployee())


Anil False
Anil False


In [12]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [19]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [9]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [11]:
lst=[1,0,2,5,3,6,9,5]
array=np.array(lst)



In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

NameError: name 'np' is not defined

In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

NameError: name 'np' is not defined

In [20]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [19]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [18]:
np.zeros((2,2)),dtype=np.int64)

SyntaxError: invalid syntax (<ipython-input-18-100d7e32189f>, line 1)

In [17]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [16]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [15]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column :",a1[:,2])

Slicing Column : [3 6]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column",a1[1:,])

row and column [[4 5 6]]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("First row :,a1[0]")

First row :,a1[0]


In [23]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [25]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[4.75600714 4.62261728 3.25934361 5.58738424 6.08096548 3.87584235
 6.74243084 3.90822728 4.42752842 4.06187528]
min value= 3.2593436064802965
max value= 6.742430836492382
mean value= 4.73222219198599
median value= 4.525072847770703


In [26]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [27]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [28]:
c1=np.array([(1,5),(6,9)])
c2=np.array([(1,3),(1,6)])
np.dot(c1,c2)

array([[ 6, 33],
       [15, 72]])